App\Domain\DataInteractor\DTO\Agenda\AgendaEntryDTO:
    type: entity
    repositoryClass: App\Repository\Agenda\AgendaEntryDTORepository
    table: "`agenda_entry`"
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        programmedDate:
            type: datetime
            column: programmed_date
            unique: false
            nullable: false
        completedDate:
            type: datetime
            column: completed_date
            unique: false
            nullable: true

    manyToOne:
        agenda:
            targetEntity: App\Domain\DataInteractor\DTO\Agenda\AgendaDTO
            inversedBy: entries
            joinColumn:
                name: agenda_id
                referencedColumnName: id
                nullable: false
                unique: false

        workout:
            targetEntity: App\Domain\DataInteractor\DTO\Workout\WorkoutDTO
            joinColumn:
                name: workout_id
                referencedColumnName: id
                nullable: false
                unique: false