doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        mongo_default:
            server: 'mongodb://%env(resolve:MONGO_DEFAULT_HOST)%:%env(resolve:MONGO_DEFAULT_PORT)%'
            # options: { replicaSet: '%env(resolve:MONGODB_DEFAULT_REPLICA_SET)%'}
    default_database: '%env(resolve:MONGO_DEFAULT_DB_NAME)%'
    document_managers:
        mongo_default:
            connection: mongo_default
            mappings:
                App:
                    type: xml
                    dir: '%kernel.project_dir%/config/doctrine/Documents'
                    prefix: 'App\Domain\DataInteractor\DTO'
