doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                host:     '%env(resolve:MYSQL_DEFAULT_HOST)%'
                port:     '%env(resolve:MYSQL_DEFAULT_PORT)%'
                dbname:   '%env(resolve:MYSQL_DEFAULT_DB_NAME)%'
                user:     '%env(resolve:MYSQL_USER)%'
                password: '%env(resolve:MYSQL_PASSWORD)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset:  UTF8
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App\Domain\DataInteractor\DTO'