security:
    encoders:
        Domain\DataInteractor\User\UserDTO:
            algorithm: bcrypt
            cost:      13

    providers:
        user_provider:
            entity:
                class: Domain\DataInteractor\User\UserDTO
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

        api_login:
            pattern: /api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter:       email
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api_register:
            pattern: ^/api/users/registration
            methods: [POST]
            anonymous: true
            stateless: true

        api_secured_area:
            provider:  user_provider
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - col_api.jwt_token_authenticator

    access_control:
        - { path: ^/api, roles: ROLE_USER }
