public_workout_get_many:
    path: /workouts
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Workout\WorkoutApiController::getMany

public_workout_get_single:
    path: /workouts/{workoutName}
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Workout\WorkoutApiController::getSingle

public_workout_post:
    path: /workouts
    methods: ['POST']
    controller: App\Controller\Api\PublicApi\Workout\WorkoutApiController::post


public_workout_exercise_delete:
    path: /workouts/{workoutName}/exercises/{exerciseId}
    methods: ['DELETE']
    controller: App\Controller\Api\PublicApi\Workout\ExerciseApiController::delete


public_reference_exercise_get_many:
    path: /references/exercises
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Workout\ReferenceExerciseApiController::getMany