public_api_reference:
    resource: 'public_api/public_api_reference_routes.yaml'

public_api_statistic:
    resource: 'public_api/public_api_statistic_routes.yaml'

public_api_user:
    resource: 'public_api/public_api_user_routes.yaml'

public_api_workout:
    resource: 'public_api/public_api_workout_routes.yaml'
