parameters:
    defaultUserUsername: '%env(string:DEV_DEFAULT_USER_USERNAME)%'
    autoAddToken: '%env(bool:DEV_DEFAULT_AUTO_ADD_TOKEN)%'
    wrapApiResponse: '%env(bool:WRAP_RESPONSE_API_IN_HTML)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Event\Dev\ApiCallWithoutTokenEventListener:
        arguments:
            $defaultUserUsername: '%defaultUserUsername%'
            $autoAddToken: '%autoAddToken%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: addTokenToRequest, priority: 999 }

    App\Event\Dev\WrapApiResponseInHtmlEventListener:
        arguments:
            $wrapApiResponse: '%wrapApiResponse%'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: wrapResponseInHtml, priority: 1 }
