parameters:
    app_env: '%env(resolve:APP_ENV)%'
    app_locale: '%env(resolve:APP_LOCALE)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Tools\Clock\SystemClock: ~
    App\Tools\Clock\FrozenClock: ~
    App\Tools\Clock\ClockInterface: '@App\Tools\Clock\SystemClock'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager: '@lexik_jwt_authentication.jwt_manager'
    Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface: '@Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager'
    col.security.guard.jwt_token_authenticator: '@App\Security\Guard\JWTTokenAuthenticator'
