public_agenda_get_many:
    path: /agendas
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Agenda\AgendaApiController::getMany

public_agenda_get_default:
    path: /agendas/default
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Agenda\AgendaApiController::getDefault

public_agenda_get_signle:
    path: /agendas/{id}
    requirements:
        id: '\d+'
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Agenda\AgendaApiController::getSingle