public_category_get_many:
    path: /categories
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Workout\CategoryApiController::getMany

public_workout_get_many:
    path: /workouts
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Workout\WorkoutApiController::getMany

public_workout_get_single:
    path: /workouts/{workoutName}
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Workout\WorkoutApiController::getSingle

public_workout_post:
    path: /workouts
    methods: ['POST']
    controller: App\Controller\Api\PublicApi\Workout\WorkoutApiController::post

public_workout_delete:
    path: /workouts/{workoutName}
    methods: ['DELETE']
    controller: App\Controller\Api\PublicApi\Workout\WorkoutApiController::delete


public_workout_exercise_post:
    path: /workouts/{workoutName}/exercises
    methods: ['POST']
    controller: App\Controller\Api\PublicApi\Workout\ExerciseApiController::post

public_workout_exercise_delete:
    path: /workouts/{workoutName}/exercises/{exerciseId}
    requirements:
        id: '\d+'
    methods: ['DELETE']
    controller: App\Controller\Api\PublicApi\Workout\ExerciseApiController::delete