public_user_get_current:
    path: /users/current
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\User\UserApiController::getCurrent

public_user_registration:
    path: /users/registration
    methods: ['post']
    controller: App\Controller\Api\PublicApi\User\UserApiController::registration