public_statistic_weight_get_many:
    path: /statistics/weights
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Statistic\WeightApiController::getMany

public_statistic_weight_get_default:
    path: /statistics/weights/default
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Statistic\WeightApiController::getDefault

public_statistic_weight_get_single:
    path: /statistics/weights/{id}
    requirements:
        id: '\d+'
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Statistic\WeightApiController::getMany
    
public_statistic_measurement_get_many:
    path: /statistics/measurements
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Statistic\MeasurementApiController::getMany

public_statistic_measurement_get_default:
    path: /statistics/measurements/default
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Statistic\MeasurementApiController::getDefault

public_statistic_measurement_get_single:
    path: /statistics/measurements/{id}
    requirements:
        id: '\d+'
    methods: ['GET']
    controller: App\Controller\Api\PublicApi\Statistic\MeasurementApiController::getMany