App\Domain\DataInteractor\DTO\Workout\ReferenceExerciseDTO:
    type: entity
    repositoryClass: App\Repository\Workout\ReferenceExerciseDTORepository
    table: "`reference_exercise`"
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 75
            unique: false
            nullable: false
        videoLink:
            type: string
            length: 255
            unique: false
            nullable: true

    manyToMany:
        referenceEquipments:
            targetEntity: App\Domain\DataInteractor\DTO\Workout\ReferenceEquipmentDTO
            joinTable:
                name: ref_exercise_has_ref_equipment
                joinColumns:
                    ref_exercise:
                        referencedColumnName: id
                inverseJoinColumns:
                    ref_equipment:
                        referencedColumnName: id
