App\Domain\DataInteractor\DTO\Statistic\WeightDTO:
    type: entity
    repositoryClass: App\Repository\Statistic\WeightDTORepository
    table: "`weight`"
    indexes:
        user_index:
            columns: [ user_id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        totalWeight:
            type: float
            unique: false
            nullable: false
            
        bodyMassIndex:
            type: float
            unique: false
            nullable: true

        bodyFatPercent:
            type: float
            unique: false
            nullable: true

    manyToOne:
        user:
            targetEntity: App\Domain\DataInteractor\DTO\User\UserDTO
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                unique: false

