App\Domain\DataInteractor\DTO\User\UserDTO:
    type: entity
    repositoryClass: App\Repository\User\UserDTORepository
    table: "`user`"
    indexes:
        username_index:
            columns: [ username ]
        email_index:
            columns: [ email ]
        type_index:
            columns: [ type ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        username:
            type: string
            length: 50
            unique: true
            nullable: false
        email:
            type: string
            length: 100
            column: email
            unique: true
            nullable: false
        password:
            type: string
            length: 255
            unique: false
            nullable: false
        type:
            type: string
            length: 255
            unique: false
            nullable: false
