App\Domain\DataInteractor\DTO\Workout\ReferenceEquipmentDTO:
    type: entity
    repositoryClass: App\Repository\Workout\ReferenceEquipmentDTORepository
    table: "`reference_equipment`"
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 75
            unique: false
            nullable: false
        amazonLink:
            type: string
            length: 255
            unique: false
            nullable: true